version: '3.8'
services:
  blazor-app:
    image: bulanec/dockerhub_bulanec:learntisimo-blazor-app
    ports:
      - "80:7142"
      - "443:7142"
    depends_on:
      - backend

  backend:
    image: bulanec/dockerhub_bulanec:learntisimo-backend
    ports:
      - '8080:8080'
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: